# ref: https://mise.jdx.dev/tasks/
#:schema https://mise.jdx.dev/schema/mise-task.json

[commit]
depends = ["buni"]
run = ["git add .", "bun run git-cz"]

["commit:staged"]
depends = ["buni"]
run = "bun run git-cz"

["build"]
run = "json5 src/default.json5 --out-file default.json"
depends_post = [
	"{% if env.CI is defined %}util:nodiff{% else %}util:donothing{% endif %}",
]

[check]
depends = ["check:*"]

["check:biome"]
run = "biome {% if env.LINT is undefined %}check --write{% else %}ci{% endif %} --error-on-warnings"

["check:tsc"]
depends = ["buni"]
run = "bun run tsc {% if env.CI is defined %}--incremental false{% endif %}"

["check:jsonschema"]
depends = ["buni"]
run = "bun run scripts/validate-json-schema.ts"

["check:actionlint"]
run = "actionlint -color"
# SC2312: check-extra-masked-returns
# pipefail is set by shell: bash in GitHub Actions but cannot be detected by shellcheck
# ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
env = { "SHELLCHECK_OPTS" = "--enable=all --exclude=SC2312" }

["check:ghalint"]
wait_for = ["check:pinact"]
run = "ghalint run"

["check:pinact"]
run = "pinact run --verify"
depends_post = [
	"{% if env.CI is defined %}util:nodiff{% else %}util:donothing{% endif %}",
]

["check:taplo"]
run = [
	"taplo lint",
	"taplo fmt {% if env.LINT is undefined %}--check --diff{% endif %}",
]

["check:prettier"]
run = """
prettier {% if env.LINT is undefined %}--write{% else %}--check{% endif %} \
	{% if env.CI is undefined %}--cache{% endif %} ."""

["check:yamlfmt"]
run = "yamlfmt {% if env.LINT is defined %}-lint{% endif %} ."

["check:yamllint"]
run = "yamllint --strict ."

["check:renovate"]
run = [
	"renovate-config-validator --strict",
	"renovate-config-validator --strict src/default.json5",
	"renovate-config-validator --strict default.json",
]

["check:cspell"]
run = "cspell {% if env.CI is undefined %}--cache{% endif %} \"**/*\""

["check:lychee"]
run = """
lychee {% if env.LINT is defined %}--verbose{% endif %} \
	{% if env.CI is undefined %}--cache{% endif %} \"**/*\""""

["check:typos"]
run = "typos {% if env.LINT is undefined %}--write-changes{% endif %}"

["check:ignore-sync"]
run = "ignore-sync ."
depends_post = [
	"{% if env.CI is defined %}util:nodiff{% else %}util:donothing{% endif %}",
]

["buni"]
run = "bun install --frozen-lockfile"

["util:nodiff"] # cspell:ignore nodiff
run = ["git add .", "git diff --staged --exit-code"]
hide = true

# cspell:ignore donothing
["util:donothing"]
run = ""
hide = true
